//go:build ignore

/**
 * Generate TypeScript types
 */

package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"reflect"
	"strings"

	"github.com/urnetwork/sdk"
)

func main() {
	check := flag.Bool("check", false, "compare against committed output without writing it")
	flag.Parse()
	output, err := generateTypes()
	if err == nil {
		const outputPath = "src/generated/types.ts"
		if *check {
			current, readErr := os.ReadFile(outputPath)
			if readErr != nil || !bytes.Equal(current, output) {
				err = fmt.Errorf("%s is stale; run `make generate_types` and commit the result", outputPath)
			}
		} else if err = os.MkdirAll("src/generated", 0755); err == nil {
			err = os.WriteFile(outputPath, output, 0644)
		}
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating types: %v\n", err)
		os.Exit(1)
	}
	if *check {
		fmt.Println("Generated TypeScript types are up to date")
	} else {
		fmt.Println("Generated TypeScript types successfully")
	}
}

func generateTypes() ([]byte, error) {
	var output strings.Builder

	output.WriteString("// Auto-generated TypeScript types from Go structs\n")
	output.WriteString("// DO NOT EDIT - Generated by: go run gen_types.go\n\n")

	// Generate types for key structs
	types := []interface{}{
		sdk.NetworkSpaceKey{},
		sdk.NetworkSpaceValues{},
		sdk.ExportNetworkSpace{},
		sdk.NetExtender{},
		sdk.ProxyAuthResult{},
		sdk.ProxyConfigResult{},
		sdk.WgConfig{},

		/**
		 * Api types
		 */
		sdk.ApiError{},
		sdk.GetPointsLeaderboardArgs{},
		sdk.PointsLeaderboardRow{},
		sdk.PointsLeaderboardResult{},
		sdk.PointsLeaderboardError{},
		sdk.PointsLeaderboardScrollLabelParts{},
		sdk.SetPointsLeaderboardPublicArgs{},
		sdk.SetPointsLeaderboardPublicResult{},
		sdk.SetPointsLeaderboardPublicError{},
		sdk.SetEmojiTagArgs{},
		sdk.SetEmojiTagResult{},
		sdk.SetEmojiTagError{},
		sdk.EmojiTagValidation{},
		// Auth login types
		sdk.AuthLoginWithPasswordArgs{},
		sdk.AuthLoginWithPasswordResult{},
		sdk.AuthLoginWithPasswordResultVerification{},
		sdk.AuthLoginWithPasswordResultNetwork{},
		sdk.AuthLoginArgs{},
		sdk.NetworkCheckArgs{},
		sdk.NetworkCheckResult{},
		sdk.NetworkCreateArgs{},
		sdk.NetworkCreateResult{},
		// onboarding program
		sdk.PriceTier{},
		sdk.OnboardingOffer{},
		sdk.ExperimentAssignment{},
		sdk.OnboardingError{},
		sdk.OnboardingOfferIssueArgs{},
		sdk.OnboardingOfferIssueResult{},
		sdk.ClientEvent{},
		sdk.ClientEventRejection{},
		sdk.ClientEventsSendArgs{},
		sdk.ClientEventsSendResult{},
		sdk.StripePaymentSheetArgs{},
		sdk.StripePaymentSheetResult{},
		sdk.StripePricesResult{},
		sdk.OnboardingClickArgs{},
		sdk.OnboardingClickResult{},
		sdk.OnboardingFeedbackTokenResult{},
		sdk.PriceEquivalent{},
		sdk.NetworkCreateResultError{},
		sdk.NetworkCreateResultVerification{},
		sdk.NetworkCreateResultNetwork{},
		sdk.WalletAuthArgs{},
		sdk.StringList{},
		sdk.AuthLoginResult{},
		sdk.AuthLoginResultError{},
		sdk.AuthLoginResultNetwork{},
		sdk.AuthVerifyArgs{},
		sdk.AuthVerifyResult{},
		sdk.AuthVerifyResultNetwork{},
		sdk.AuthVerifySendError{},
		sdk.AuthCodeLoginArgs{},
		sdk.AuthCodeLoginResult{},
		sdk.AuthNetworkClientResult{},
		sdk.ProviderSpec{},
		sdk.AuthNetworkClientError{},
		sdk.AuthNetworkClientArgs{},
		sdk.ProxyConfig{},
		sdk.FindLocationsArgs{},
		sdk.FindLocationsResult{},
		sdk.LocationResult{},
		sdk.LocationGroupResult{},
		sdk.LocationDeviceResult{},
		sdk.FilteredLocations{},
		sdk.RegionGroup{},
		sdk.ConnectLocationId{},
		sdk.ConnectLocation{},
		sdk.ProxyDeviceState{},
		sdk.PerformanceProfile{},
		sdk.WindowSizeSettings{},
		sdk.RemoveNetworkClientArgs{},
		sdk.RemoveNetworkClientResult{},
		sdk.CreateApiKeyArgs{},
		sdk.CreateApiKeyResult{},
		sdk.PublicAccountApiKey{},
		sdk.ListApiKeysResult{},
		sdk.DeleteApiKeyArgs{},
		sdk.DeleteApiKeyResult{},
		// UR protocol (subnet 25) earnings
		sdk.SnChainSettings{},
		sdk.SnError{},
		sdk.SnWallet{},
		sdk.SnSetWalletArgs{},
		sdk.SnSetWalletResult{},
		sdk.SnSetWalletError{},
		sdk.SnGetWalletResult{},
		sdk.SnValidateWalletArgs{},
		sdk.SnValidateWalletResult{},
		sdk.SnConnectWalletResult{},
		sdk.SnGasKey{},
		sdk.SnGasBalanceResult{},
		sdk.SnEpochClaim{},
		sdk.SnClaimsResult{},
		sdk.SnUnsignedTx{},
		sdk.SnEpochResult{},
		sdk.AccountEpoch{},
		sdk.AccountEpochsResult{},
		sdk.SnHeadResult{},
	}

	for _, t := range types {
		ts, err := generateTypeScriptInterface(t)
		if err != nil {
			return nil, err
		}
		output.WriteString(ts)
		output.WriteString("\n\n")
	}

	return []byte(output.String()), nil
}

func generateTypeScriptInterface(v interface{}) (string, error) {
	t := reflect.TypeOf(v)
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("export interface %s {\n", t.Name()))

	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)

		// Skip unexported fields
		if !field.IsExported() {
			continue
		}

		// Get JSON tag
		jsonTag := field.Tag.Get("json")
		if jsonTag == "-" {
			continue
		}

		jsonName, optional := parseJSONTag(jsonTag)
		if jsonName == "" {
			jsonName = toSnakeCase(field.Name)
		}

		// Map Go type to TypeScript type
		tsType := goTypeToTypeScript(field.Type)

		optionalMarker := ""
		if optional {
			optionalMarker = "?"
		}

		sb.WriteString(fmt.Sprintf("  %s%s: %s;\n", jsonName, optionalMarker, tsType))
	}

	// fields written by a custom MarshalJSON rather than a struct field
	switch t.String() {
	case "sdk.SnChainSettings":
		sb.WriteString("  rpc_urls?: string[];\n")
	}

	sb.WriteString("}")
	return sb.String(), nil
}

func parseJSONTag(tag string) (name string, optional bool) {
	if tag == "" {
		return "", false
	}

	parts := strings.Split(tag, ",")
	name = parts[0]

	for _, part := range parts[1:] {
		if part == "omitempty" {
			optional = true
		}
	}

	return name, optional
}

func goTypeToTypeScript(t reflect.Type) string {
	// Handle pointers
	if t.Kind() == reflect.Ptr {
		return goTypeToTypeScript(t.Elem()) + " | null"
	}

	// Handle basic types
	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Slice:
		elemType := goTypeToTypeScript(t.Elem())
		return elemType + "[]"
	case reflect.Map:
		keyType := goTypeToTypeScript(t.Key())
		valueType := goTypeToTypeScript(t.Elem())
		return fmt.Sprintf("Record<%s, %s>", keyType, valueType)
	case reflect.Struct:
		// Check for known types
		switch t.String() {
		case "time.Time", "sdk.Time":
			return "string" // ISO 8601 format
		case "netip.Addr":
			return "string"
		case "sdk.Id":
			return "string" // UUID format
		case "sdk.StringList":
			return "string[]"
		case "sdk.LocationResultList":
			return "LocationResult[]"
		case "sdk.LocationDeviceResultList":
			return "LocationDeviceResult[]"
		case "sdk.ProviderSpecList":
			return "ProviderSpec[]"
		case "sdk.LocationGroupResultList":
			return "LocationGroupResult[]"
		case "sdk.ConnectLocationList":
			return "ConnectLocation[]"
		case "sdk.RegionGroupList":
			return "RegionGroup[]"
		case "sdk.PublicAccountApiKeyList":
			return "PublicAccountApiKey[]"
		case "sdk.Int64List":
			return "number[]"
		case "sdk.SnWalletList":
			return "SnWallet[]"
		case "sdk.SnEpochClaimList":
			return "SnEpochClaim[]"
		case "sdk.SnUnsignedTxList":
			return "SnUnsignedTx[]"
		case "sdk.AccountEpochList":
			return "AccountEpoch[]"
		case "sdk.PointsLeaderboardRowList":
			return "PointsLeaderboardRow[]"
		case "sdk.ClientEventList":
			return "ClientEvent[]"
		case "sdk.ClientEventRejectionList":
			return "ClientEventRejection[]"
		case "sdk.ExperimentAssignmentList":
			// custom json: an object keyed by surface
			return "Record<string, ExperimentAssignment>"
		case "sdk.PointsLeaderboardMe":
			// custom json: the row's fields with points_leaderboard_public and
			// ranked beside them
			return "PointsLeaderboardRow & { points_leaderboard_public: boolean; ranked: boolean }"
		default:
			return t.Name()
		}
	}

	return "any"
}

func toSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result.WriteRune('_')
		}
		result.WriteRune(r)
	}
	return strings.ToLower(result.String())
}
