<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>URnetwork.SDK</PackageId>
    <Version>0.0.1-dev.0</Version>
    <Authors>URnetwork</Authors>
    <Description>URnetwork userspace networking SDK over the CGo native library</Description>
    <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/urnetwork/sdk</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="/" />
    <None Include="runtimes/**/*" Pack="true" PackagePath="runtimes/" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
