package sdk

import (
	_ "embed"
	"encoding/json"
	"slices"
	"strings"
	"sync"
)

// license.yml is the open source license and data attribution list every app
// shows under Account -> Settings -> Licenses. It is generated by
// `go run ./licenses` (see licenses/main.go) from the SDK's Go modules, the
// apps' own dependencies in the sibling repos, and the hand-kept
// licenses/extra.yml. The same generator writes license_data.json for runtime
// embedding, so shipping apps do not need a YAML parser for this static data.
// Both files are checked for parity by the license gate. Do not edit by hand.
//
//go:embed license_data.json
var licenseJSON []byte

// the apps a license entry can apply to. An app passes its own to GetLicenses.
const (
	LicenseAppAndroid   = "android"
	LicenseAppApple     = "apple"
	LicenseAppWindows   = "windows"
	LicenseAppLinux     = "linux"
	LicenseAppWeb       = "web"
	LicenseAppExtension = "extension"
)

// the kinds of license entries
const (
	LicenseKindData     = "data"
	LicenseKindSoftware = "software"
	LicenseKindFont     = "font"
)

// LicenseInfo is one component the app includes, and the license and notice
// that must be published with it.
type LicenseInfo struct {
	// display name, e.g. "github.com/pion/webrtc/v4" or "GeoLite2"
	Name    string
	Version string
	// LicenseKindData, LicenseKindSoftware or LicenseKindFont
	Kind string
	// the collector the entry came from: go, maven, swiftpm, npm-web,
	// npm-extension, or extra (licenses/extra.yml: data, fonts, vendored code)
	Origin string
	// the project home page
	Url string
	// SPDX license expression, or empty when the text is not a standard license
	Spdx string
	// copyright lines found in the license text, newline separated
	Copyright string
	// a notice that must be shown verbatim, e.g. the MaxMind attribution.
	// Empty for most entries.
	Notice string
	// the full license text
	Text string
}

type LicenseInfoList struct {
	exportedList[*LicenseInfo]
}

func NewLicenseInfoList() *LicenseInfoList {
	return &LicenseInfoList{
		exportedList: *newExportedList[*LicenseInfo](),
	}
}

// The shared license.yml / license_data.json schema. YAML tags are used only
// by the parity test; the runtime imports encoding/json, already used by the SDK.
type licenseFile struct {
	Entries []licenseFileEntry `yaml:"entries" json:"entries"`
	Texts   map[string]string  `yaml:"texts" json:"texts"`
}

type licenseFileEntry struct {
	Name      string   `yaml:"name" json:"name"`
	Version   string   `yaml:"version,omitempty" json:"version,omitempty"`
	Kind      string   `yaml:"kind" json:"kind"`
	Origin    string   `yaml:"origin" json:"origin"`
	Apps      []string `yaml:"apps" json:"apps"`
	Url       string   `yaml:"url,omitempty" json:"url,omitempty"`
	Spdx      string   `yaml:"spdx,omitempty" json:"spdx,omitempty"`
	Copyright string   `yaml:"copyright,omitempty" json:"copyright,omitempty"`
	Notice    string   `yaml:"notice,omitempty" json:"notice,omitempty"`
	Text      string   `yaml:"text" json:"text"`
}

var loadLicenseFile = sync.OnceValues(func() (*licenseFile, error) {
	var f licenseFile
	if err := json.Unmarshal(licenseJSON, &f); err != nil {
		return nil, err
	}
	return &f, nil
})

// GetLicenses returns the entries that apply to `app` (one of the LicenseApp*
// constants), in display order: data attributions first, then software and
// fonts by name. An empty `app` returns every entry.
func GetLicenses(app string) *LicenseInfoList {
	licenses := NewLicenseInfoList()
	f, err := loadLicenseFile()
	if err != nil {
		// the embedded file is checked by TestLicenseCatalogParses; this cannot
		// happen in a released build
		return licenses
	}
	for _, entry := range f.Entries {
		if app != "" && !slices.Contains(entry.Apps, app) {
			continue
		}
		licenses.Add(&LicenseInfo{
			Name:      entry.Name,
			Version:   entry.Version,
			Kind:      entry.Kind,
			Origin:    entry.Origin,
			Url:       entry.Url,
			Spdx:      entry.Spdx,
			Copyright: entry.Copyright,
			Notice:    entry.Notice,
			Text:      strings.TrimRight(f.Texts[entry.Text], "\n"),
		})
	}
	return licenses
}
