/* Code generated by gen/gen.go. DO NOT EDIT. */
#include "callbacks.h"

void urnet_invoke_account_preferences_get(urnet_account_preferences_get_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_account_preferences_set(urnet_account_preferences_set_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_account_wallets(urnet_account_wallets_cb cb, void* user_data) {
	cb(user_data);
}

void urnet_invoke_active_network_space_change(urnet_active_network_space_change_cb cb, void* user_data, uint64_t network_space) {
	cb(user_data, network_space);
}

void urnet_invoke_allow_foreground_change(urnet_allow_foreground_change_cb cb, void* user_data, bool allow_foreground) {
	cb(user_data, allow_foreground);
}

void urnet_invoke_allow_product_updates(urnet_allow_product_updates_cb cb, void* user_data, bool p0) {
	cb(user_data, p0);
}

void urnet_invoke_auth_code_create(urnet_auth_code_create_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_auth_code_login(urnet_auth_code_login_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_auth_login(urnet_auth_login_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_auth_login_with_password(urnet_auth_login_with_password_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_auth_logout(urnet_auth_logout_cb cb, void* user_data) {
	cb(user_data);
}

void urnet_invoke_auth_network_client(urnet_auth_network_client_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_auth_password_reset(urnet_auth_password_reset_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_auth_verify(urnet_auth_verify_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_auth_verify_send(urnet_auth_verify_send_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_block_action_overrides_change(urnet_block_action_overrides_change_cb cb, void* user_data, const char* block_action_overrides_json) {
	cb(user_data, block_action_overrides_json);
}

void urnet_invoke_block_action_stats(urnet_block_action_stats_cb cb, void* user_data) {
	cb(user_data);
}

void urnet_invoke_block_action_window_change(urnet_block_action_window_change_cb cb, void* user_data, const char* block_action_window_json) {
	cb(user_data, block_action_window_json);
}

void urnet_invoke_block_actions(urnet_block_actions_cb cb, void* user_data) {
	cb(user_data);
}

void urnet_invoke_block_stats_change(urnet_block_stats_change_cb cb, void* user_data, const char* block_stats_json) {
	cb(user_data, block_stats_json);
}

void urnet_invoke_blocker_enabled_change(urnet_blocker_enabled_change_cb cb, void* user_data, bool blocker_enabled) {
	cb(user_data, blocker_enabled);
}

void urnet_invoke_can_prompt_intro_funnel_change(urnet_can_prompt_intro_funnel_change_cb cb, void* user_data, bool can_prompt_intro_funnel) {
	cb(user_data, can_prompt_intro_funnel);
}

void urnet_invoke_can_refer_change(urnet_can_refer_change_cb cb, void* user_data, bool can_refer) {
	cb(user_data, can_refer);
}

void urnet_invoke_can_show_rating_dialog_change(urnet_can_show_rating_dialog_change_cb cb, void* user_data, bool can_show_rating_dialog) {
	cb(user_data, can_show_rating_dialog);
}

void urnet_invoke_commit(urnet_commit_cb cb, void* user_data, bool success) {
	cb(user_data, success);
}

void urnet_invoke_connect_change(urnet_connect_change_cb cb, void* user_data, bool connect_enabled) {
	cb(user_data, connect_enabled);
}

void urnet_invoke_connect_location_change(urnet_connect_location_change_cb cb, void* user_data, const char* location_json) {
	cb(user_data, location_json);
}

void urnet_invoke_connection_status(urnet_connection_status_cb cb, void* user_data) {
	cb(user_data);
}

void urnet_invoke_contract_details_change(urnet_contract_details_change_cb cb, void* user_data, const char* contract_details_json) {
	cb(user_data, contract_details_json);
}

void urnet_invoke_contract_stats_change(urnet_contract_stats_change_cb cb, void* user_data, const char* contract_stats_json) {
	cb(user_data, contract_stats_json);
}

void urnet_invoke_contract_status_change(urnet_contract_status_change_cb cb, void* user_data, const char* contract_status_json) {
	cb(user_data, contract_status_json);
}

void urnet_invoke_create_account_wallet(urnet_create_account_wallet_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_create_api_key(urnet_create_api_key_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_default_location_change(urnet_default_location_change_cb cb, void* user_data, const char* location_json) {
	cb(user_data, location_json);
}

void urnet_invoke_delete_api_key(urnet_delete_api_key_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_device_recreated(urnet_device_recreated_cb cb, void* user_data) {
	cb(user_data);
}

void urnet_invoke_device_set_name(urnet_device_set_name_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_dns_resolver_settings_change(urnet_dns_resolver_settings_change_cb cb, void* user_data, const char* dns_resolver_settings_json) {
	cb(user_data, dns_resolver_settings_json);
}

void urnet_invoke_filtered_locations(urnet_filtered_locations_cb cb, void* user_data, const char* locations_json, const char* state) {
	cb(user_data, locations_json, state);
}

void urnet_invoke_find_locations(urnet_find_locations_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_find_providers2(urnet_find_providers2_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_find_providers(urnet_find_providers_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_get_account_payments(urnet_get_account_payments_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_get_account_points(urnet_get_account_points_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_get_account_wallets(urnet_get_account_wallets_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_get_by_client_jwt(urnet_get_by_client_jwt_cb cb, void* user_data, const char* result, bool ok_param) {
	cb(user_data, result, ok_param);
}

void urnet_invoke_get_by_jwt(urnet_get_by_jwt_cb cb, void* user_data, const char* result, bool ok_param) {
	cb(user_data, result, ok_param);
}

void urnet_invoke_get_instance_id(urnet_get_instance_id_cb cb, void* user_data, const char* result, bool ok_param) {
	cb(user_data, result, ok_param);
}

void urnet_invoke_get_leaderboard(urnet_get_leaderboard_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_get_network_blocked_locations(urnet_get_network_blocked_locations_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_get_network_clients(urnet_get_network_clients_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_get_network_leaderboard_ranking(urnet_get_network_leaderboard_ranking_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_get_network_redeemed_balance_codes(urnet_get_network_redeemed_balance_codes_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_get_network_referral_code(urnet_get_network_referral_code_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_get_network_reliability(urnet_get_network_reliability_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_get_network_user(urnet_get_network_user_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_get_payout_wallet(urnet_get_payout_wallet_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_get_referral_network(urnet_get_referral_network_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_get_transfer_stats(urnet_get_transfer_stats_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_grid(urnet_grid_cb cb, void* user_data) {
	cb(user_data);
}

void urnet_invoke_io_loop_done(urnet_io_loop_done_cb cb, void* user_data) {
	cb(user_data);
}

void urnet_invoke_is_creating_external_wallet(urnet_is_creating_external_wallet_cb cb, void* user_data, bool p0) {
	cb(user_data, p0);
}

void urnet_invoke_is_network_user_loading(urnet_is_network_user_loading_cb cb, void* user_data, bool p0) {
	cb(user_data, p0);
}

void urnet_invoke_is_network_user_updating(urnet_is_network_user_updating_cb cb, void* user_data, bool p0) {
	cb(user_data, p0);
}

void urnet_invoke_is_removing_wallet(urnet_is_removing_wallet_cb cb, void* user_data, bool p0) {
	cb(user_data, p0);
}

void urnet_invoke_is_sending_feedback(urnet_is_sending_feedback_cb cb, void* user_data, bool p0) {
	cb(user_data, p0);
}

void urnet_invoke_jwt_refresh(urnet_jwt_refresh_cb cb, void* user_data, const char* jwt) {
	cb(user_data, jwt);
}

void urnet_invoke_list_api_keys(urnet_list_api_keys_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_local_override_app_ids(urnet_local_override_app_ids_cb cb, void* user_data) {
	cb(user_data);
}

void urnet_invoke_network_block_location(urnet_network_block_location_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_network_check(urnet_network_check_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_network_clients(urnet_network_clients_cb cb, void* user_data, const char* network_clients_json) {
	cb(user_data, network_clients_json);
}

void urnet_invoke_network_create(urnet_network_create_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_network_delete(urnet_network_delete_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_network_peers_change(urnet_network_peers_change_cb cb, void* user_data, const char* network_peers_json) {
	cb(user_data, network_peers_json);
}

void urnet_invoke_network_space_update(urnet_network_space_update_cb cb, void* user_data, const char* values_json) {
	cb(user_data, values_json);
}

void urnet_invoke_network_spaces_change(urnet_network_spaces_change_cb cb, void* user_data) {
	cb(user_data);
}

void urnet_invoke_network_unblock_location(urnet_network_unblock_location_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_network_user(urnet_network_user_cb cb, void* user_data) {
	cb(user_data);
}

void urnet_invoke_network_user_update(urnet_network_user_update_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_network_user_update_error(urnet_network_user_update_error_cb cb, void* user_data, const char* p0) {
	cb(user_data, p0);
}

void urnet_invoke_network_user_update_success(urnet_network_user_update_success_cb cb, void* user_data) {
	cb(user_data);
}

void urnet_invoke_offline_change(urnet_offline_change_cb cb, void* user_data, bool offline, bool vpn_interface_while_offline) {
	cb(user_data, offline, vpn_interface_while_offline);
}

void urnet_invoke_packet_stats_change(urnet_packet_stats_change_cb cb, void* user_data, const char* packet_stats_json) {
	cb(user_data, packet_stats_json);
}

void urnet_invoke_parse_by_jwt(urnet_parse_by_jwt_cb cb, void* user_data, const char* result_json, bool ok_param) {
	cb(user_data, result_json, ok_param);
}

void urnet_invoke_payments(urnet_payments_cb cb, void* user_data) {
	cb(user_data);
}

void urnet_invoke_payout_wallet(urnet_payout_wallet_cb cb, void* user_data, const char* p0) {
	cb(user_data, p0);
}

void urnet_invoke_performance_profile_change(urnet_performance_profile_change_cb cb, void* user_data, const char* performance_profile_json) {
	cb(user_data, performance_profile_json);
}

void urnet_invoke_provide_change(urnet_provide_change_cb cb, void* user_data, bool provide_enabled) {
	cb(user_data, provide_enabled);
}

void urnet_invoke_provide_control_mode_change(urnet_provide_control_mode_change_cb cb, void* user_data, const char* provide_control_mode) {
	cb(user_data, provide_control_mode);
}

void urnet_invoke_provide_mode_change(urnet_provide_mode_change_cb cb, void* user_data, int64_t provide_mode) {
	cb(user_data, provide_mode);
}

void urnet_invoke_provide_network_mode_change(urnet_provide_network_mode_change_cb cb, void* user_data, const char* provide_network_mode) {
	cb(user_data, provide_network_mode);
}

void urnet_invoke_provide_paused_change(urnet_provide_paused_change_cb cb, void* user_data, bool provide_paused) {
	cb(user_data, provide_paused);
}

void urnet_invoke_provide_secret_keys(urnet_provide_secret_keys_cb cb, void* user_data, const char* provide_secret_key_list_json) {
	cb(user_data, provide_secret_key_list_json);
}

void urnet_invoke_receive_packet(urnet_receive_packet_cb cb, void* user_data, int64_t ip_version, int64_t ip_protocol, const uint8_t* packet, int32_t packet_len) {
	cb(user_data, ip_version, ip_protocol, packet, packet_len);
}

void urnet_invoke_redeem_balance_code(urnet_redeem_balance_code_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_referral_code(urnet_referral_code_cb cb, void* user_data, const char* p0) {
	cb(user_data, p0);
}

void urnet_invoke_refresh_jwt(urnet_refresh_jwt_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_remote_change(urnet_remote_change_cb cb, void* user_data, bool remote_connected) {
	cb(user_data, remote_connected);
}

void urnet_invoke_remove_wallet(urnet_remove_wallet_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_route_local_change(urnet_route_local_change_cb cb, void* user_data, bool route_local) {
	cb(user_data, route_local);
}

void urnet_invoke_selected_location(urnet_selected_location_cb cb, void* user_data, const char* location_json) {
	cb(user_data, location_json);
}

void urnet_invoke_send_feedback(urnet_send_feedback_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_set_network_leaderboard_public(urnet_set_network_leaderboard_public_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_set_network_referral(urnet_set_network_referral_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_set_payout_wallet(urnet_set_payout_wallet_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

bool urnet_invoke_setup_new_device(urnet_setup_new_device_cb cb, void* user_data, uint64_t device, const char* proxy_config_result_json) {
	return cb(user_data, device, proxy_config_result_json);
}

void urnet_invoke_solana_payment_intent(urnet_solana_payment_intent_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_stripe_create_checkout_session(urnet_stripe_create_checkout_session_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_stripe_create_customer_portal(urnet_stripe_create_customer_portal_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_stripe_payment_intent(urnet_stripe_payment_intent_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_subscription_balance(urnet_subscription_balance_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_subscription_create_payment_id(urnet_subscription_create_payment_id_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_throughput(urnet_throughput_cb cb, void* user_data) {
	cb(user_data);
}

void urnet_invoke_tunnel_change(urnet_tunnel_change_cb cb, void* user_data, bool tunnel_started) {
	cb(user_data, tunnel_started);
}

void urnet_invoke_unlink_referral_network(urnet_unlink_referral_network_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_unpaid_byte_count(urnet_unpaid_byte_count_cb cb, void* user_data, int64_t p0) {
	cb(user_data, p0);
}

void urnet_invoke_upgrade_guest(urnet_upgrade_guest_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_upgrade_guest_existing(urnet_upgrade_guest_existing_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_upload_logs(urnet_upload_logs_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_validate_address(urnet_validate_address_cb cb, void* user_data, bool valid) {
	cb(user_data, valid);
}

void urnet_invoke_validate_referral_code(urnet_validate_referral_code_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_verify_seeker_nft_holder(urnet_verify_seeker_nft_holder_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_view_controller_close(urnet_view_controller_close_cb cb, void* user_data) {
	cb(user_data);
}

void urnet_invoke_view_controller_start(urnet_view_controller_start_cb cb, void* user_data) {
	cb(user_data);
}

void urnet_invoke_view_controller_stop(urnet_view_controller_stop_cb cb, void* user_data) {
	cb(user_data);
}

void urnet_invoke_vpn_interface_while_offline_change(urnet_vpn_interface_while_offline_change_cb cb, void* user_data, bool vpn_interface_while_offline) {
	cb(user_data, vpn_interface_while_offline);
}

void urnet_invoke_wallet_balance(urnet_wallet_balance_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_wallet_circle_init(urnet_wallet_circle_init_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_wallet_circle_transfer_out(urnet_wallet_circle_transfer_out_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_wallet_validate_address(urnet_wallet_validate_address_cb cb, void* user_data, const char* result_json, const char* err_param) {
	cb(user_data, result_json, err_param);
}

void urnet_invoke_window_status_change(urnet_window_status_change_cb cb, void* user_data, const char* window_status_json) {
	cb(user_data, window_status_json);
}

