/* HAND-WRITTEN. callbacks.h next to this file is generated by gen/gen.go from the VPN sdk's
 * listener interfaces and carries "DO NOT EDIT"; the messaging surface is hand-written
 * (see exports_message.go for why), so its one callback shim lives here instead of being
 * added to a generated file that the next `make generate` would overwrite. */
#ifndef URNETWORK_MESSAGE_CALLBACKS_H
#define URNETWORK_MESSAGE_CALLBACKS_H

#include <stdint.h>
#include <stdbool.h>

/* One Hello that did not connect, as urmessage.ConnectPolicy.OnAttempt sees it. Fires on a
 * goroutine inside urnet_message_device_connect, which is the CALLER'S OWN THREAD: this is a
 * progress report from a blocking call, not an async completion. It must not call back into
 * the device it came from. err is only valid during the call. */
typedef void (*urnet_message_connect_attempt_cb)(void* user_data, int32_t attempt, int64_t elapsed_ms, int64_t backoff_ms, const char* err);
void urnet_invoke_message_connect_attempt(urnet_message_connect_attempt_cb cb, void* user_data, int32_t attempt, int64_t elapsed_ms, int64_t backoff_ms, const char* err);

#endif
