// Code generated by gen/gen.go. DO NOT EDIT.

//go:build !windows

package main

/*
#include <stdint.h>
#include <stdbool.h>
#include "callbacks.h"
*/
import "C"

import (
	"unsafe"

	"github.com/urnetwork/sdk"
)

var _ = unsafe.Pointer(nil)

type cAdapterIoLoopDoneCallback struct {
	cbIoLoopDone C.urnet_io_loop_done_cb
	userData     unsafe.Pointer
}

func (self *cAdapterIoLoopDoneCallback) IoLoopDone() {
	defer cgoGuard("urnet_io_loop_done_cb")
	C.urnet_invoke_io_loop_done(self.cbIoLoopDone, self.userData)
}

//export urnet_io_loop_close
func urnet_io_loop_close(self C.uint64_t) {
	defer cgoGuard("urnet_io_loop_close")
	self_, ok := resolveHandle[*sdk.IoLoop](uint64(self), "urnet_io_loop_close")
	if !ok {
		return
	}
	self_.Close()
}

//export urnet_new_io_loop
func urnet_new_io_loop(deviceLocal C.uint64_t, fd C.int64_t, doneCallback_io_loop_done C.urnet_io_loop_done_cb, doneCallback_user_data unsafe.Pointer) C.uint64_t {
	defer cgoGuard("urnet_new_io_loop")
	deviceLocal_, ok := resolveHandle[*sdk.DeviceLocal](uint64(deviceLocal), "urnet_new_io_loop")
	if !ok {
		return 0
	}
	var doneCallback_ sdk.IoLoopDoneCallback
	if doneCallback_io_loop_done != nil {
		doneCallback_ = &cAdapterIoLoopDoneCallback{cbIoLoopDone: doneCallback_io_loop_done, userData: doneCallback_user_data}
	}
	r0 := sdk.NewIoLoop(deviceLocal_, int32(int64(fd)), doneCallback_)
	if r0 == nil {
		return 0
	}
	return C.uint64_t(newHandle(r0))
}
