import { test } from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

// The generated api client (src/generated/openapi.ts + client.ts) is
// committed; it must equal a fresh generation from the spec of record,
// connect/api/bringyour.yml, beside sdk in the monoroot. Without connect
// (an npm consumer, a lone sdk checkout) there is nothing to compare to and
// the check is skipped.

const jsDir = fileURLToPath(new URL("..", import.meta.url));
const specUrl = new URL("../../../connect/api/bringyour.yml", import.meta.url);
const specMissing = !existsSync(specUrl);
const skip = specMissing ? "connect/api/bringyour.yml is not checked out beside sdk" : false;

const header = (relative: string) => readFileSync(new URL(relative, import.meta.url), "utf8").slice(0, 600);

test("generated client was generated from the current spec", { skip }, () => {
  const sha = createHash("sha256").update(readFileSync(specUrl)).digest("hex");
  for (const file of ["../src/generated/openapi.ts", "../src/generated/client.ts"]) {
    const match = header(file).match(/^\/\/ spec sha256: ([0-9a-f]{64})$/m);
    assert.ok(match, `${file} has no spec sha256 header`);
    assert.equal(
      match[1],
      sha,
      `${file} is stale: connect/api/bringyour.yml changed. Run \`make generate_openapi\` in sdk/js and commit the result.`,
    );
  }
});

test("generated client equals a fresh generation", { skip, timeout: 180000 }, () => {
  try {
    execFileSync("go", ["run", "gen_openapi.go", "-check"], {
      cwd: jsDir,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
  } catch (error) {
    const e = error as { code?: string; stderr?: string; stdout?: string };
    if (e.code === "ENOENT") {
      // no go toolchain: the sha check above still guards spec drift
      return;
    }
    assert.fail(`${e.stderr || ""}${e.stdout || ""}` || String(error));
  }
});

test("committed generated files carry the generator banner", () => {
  for (const file of ["../src/generated/openapi.ts", "../src/generated/client.ts"]) {
    assert.match(header(file), /DO NOT EDIT - Generated by: go run gen_openapi\.go/);
  }
});
