package merkle

// OpenZeppelin compatibility fixtures.
//
// testdata/oz_fixtures.json was generated by testdata/gen_oz_fixtures.mjs
// with the REAL OpenZeppelin JS library, @openzeppelin/merkle-tree@1.0.8
// (https://github.com/OpenZeppelin/merkle-tree), using
// StandardMerkleTree.of(values, ["bytes32", "uint256"]) — the exact leaf
// tuple shape of UR payout and effort leaves. Every fixture proof was
// re-verified with StandardMerkleTree.verify at generation time, and that
// library is OZ's reference producer for contracts checked by
// MerkleProof.verify. Testing against it (instead of against ourselves)
// pins:
//
//  1. leaf hashing — PayoutLeaf must equal OZ's standardLeafHash,
//     keccak256(bytes.concat(keccak256(abi.encode(bytes32, uint256))));
//  2. proof folding — Verify must accept genuine OZ proofs, i.e. it is
//     the same fold as MerkleProof.processProof (commutative sorted-pair
//     keccak256);
//  3. tree shape — for leaf counts where OZ's packed-array layout
//     coincides with this package's canonical shape (1, 2, 3, 8 here),
//     roots and every proof match byte-for-byte;
//  4. the documented divergence — at n=5 (verifyOnly fixtures) the OZ JS
//     array layout pairs the trailing sorted leaf earlier than the
//     canonical promoted-odd shape, so the roots MUST differ while both
//     sides' proofs still verify against their own roots. This is why the
//     canonical shape is normative for every UR root builder.

import (
	"encoding/json"
	"os"
	"testing"
)

const ozFixturesPath = "testdata/oz_fixtures.json"

type ozLeaf struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type ozCase struct {
	Name       string     `json:"name"`
	VerifyOnly bool       `json:"verifyOnly"`
	Leaves     []ozLeaf   `json:"leaves"`
	Root       string     `json:"root"`
	LeafHashes []string   `json:"leafHashes"`
	Proofs     [][]string `json:"proofs"`
}

type ozFixtureFile struct {
	Source       string   `json:"source"`
	Library      string   `json:"library"`
	LeafEncoding []string `json:"leafEncoding"`
	Cases        []ozCase `json:"cases"`
}

func loadOZFixtures(t *testing.T) ozFixtureFile {
	t.Helper()
	raw, err := os.ReadFile(ozFixturesPath)
	if err != nil {
		t.Fatal(err)
	}
	var f ozFixtureFile
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatal(err)
	}
	if len(f.Cases) == 0 {
		t.Fatal("no OZ fixture cases")
	}
	if len(f.LeafEncoding) != 2 || f.LeafEncoding[0] != "bytes32" || f.LeafEncoding[1] != "uint256" {
		t.Fatalf("unexpected fixture leaf encoding %v", f.LeafEncoding)
	}
	return f
}

func TestOZFixtures(t *testing.T) {
	fixtures := loadOZFixtures(t)
	sawVerifyOnly, sawExact := 0, 0

	for _, c := range fixtures.Cases {
		t.Run(c.Name, func(t *testing.T) {
			if len(c.LeafHashes) != len(c.Leaves) || len(c.Proofs) != len(c.Leaves) {
				t.Fatalf("malformed fixture: %d leaves, %d hashes, %d proofs",
					len(c.Leaves), len(c.LeafHashes), len(c.Proofs))
			}
			ozRoot := mustHex32(t, c.Root)

			leaves := make([]Leaf, len(c.Leaves))
			ozProofs := make([][][32]byte, len(c.Leaves))
			for i, ol := range c.Leaves {
				// (1) Our leaf hash == OZ standardLeafHash for the same tuple.
				leaves[i] = PayoutLeaf(mustHex32(t, ol.Key), mustBig(t, ol.Value))
				if hex32(leaves[i]) != c.LeafHashes[i] {
					t.Fatalf("leaf %d: PayoutLeaf = %s, OZ leafHash = %s",
						i, hex32(leaves[i]), c.LeafHashes[i])
				}
				ozProofs[i] = make([][32]byte, len(c.Proofs[i]))
				for j, h := range c.Proofs[i] {
					ozProofs[i][j] = mustHex32(t, h)
				}
				// (2) Our Verify accepts the genuine OZ proof against the OZ root.
				if !Verify(ozRoot, leaves[i], ozProofs[i]) {
					t.Fatalf("leaf %d: OZ proof rejected by Verify", i)
				}
			}

			tree := mustTree(t, leaves)
			if c.VerifyOnly {
				sawVerifyOnly++
				// (4) Shapes intentionally diverge here: OZ JS packs the tree
				// array, our canonical shape promotes the odd node. Roots must
				// differ (if they ever match, the shape analysis is wrong and
				// this test forces a second look)...
				if tree.Root() == ozRoot {
					t.Fatalf("n=%d: canonical root unexpectedly equals OZ JS root %s",
						len(leaves), c.Root)
				}
				// ...while our own proofs verify against our own root, exactly
				// as the on-chain verifier (shape-blind) will accept them.
				for i, leaf := range leaves {
					proof, err := tree.ProofAt(i)
					if err != nil {
						t.Fatal(err)
					}
					if !Verify(tree.Root(), leaf, proof) {
						t.Fatalf("leaf %d: canonical proof does not verify", i)
					}
				}
				return
			}

			sawExact++
			// (3) Coinciding shapes: root and all proofs byte-identical to OZ.
			if hex32(tree.Root()) != c.Root {
				t.Fatalf("root %s != OZ root %s", hex32(tree.Root()), c.Root)
			}
			for i := range leaves {
				proof, err := tree.ProofAt(i)
				if err != nil {
					t.Fatal(err)
				}
				if len(proof) != len(ozProofs[i]) {
					t.Fatalf("leaf %d: proof length %d != OZ %d", i, len(proof), len(ozProofs[i]))
				}
				for j := range proof {
					if proof[j] != ozProofs[i][j] {
						t.Fatalf("leaf %d proof element %d: %s != OZ %s",
							i, j, hex32(proof[j]), c.Proofs[i][j])
					}
				}
			}
		})
	}

	if sawExact < 2 || sawVerifyOnly < 1 {
		t.Fatalf("fixture coverage too thin: %d exact cases (want >= 2), %d verify-only (want >= 1)",
			sawExact, sawVerifyOnly)
	}
}
