package merkle

// Golden tests for the 9-field TrailLeaf against STSubnet.trailLeafHash.
//
// The shared vector file (testdata/merkle_vectors.json) is deliberately NOT
// extended: it is byte-regenerated by TestVectorsFileUpToDate under a strict
// {coldkey|pathId, value} leaf schema that both the Go regenerator and the
// Solidity reader (evm/test/Claims.t.sol) parse positionally — a 9-field
// section would break both consumers. Instead the expected hashes below were
// derived with Foundry's own ABI encoder + keccak, independently of this
// package:
//
//	payload = cast abi-encode \
//	    "f(uint256,bytes32,uint256,uint64,bytes32,bytes32,bytes32,bytes32,bytes32)" \
//	    <index> <pathId> <coverage> <serverKeyId> <finalDigest> \
//	    <serverSigR> <serverSigS> <vpkSigR> <vpkSigS>
//	leaf    = cast keccak $(cast keccak $payload)
//
// which is exactly keccak256(bytes.concat(keccak256(abi.encode(...)))) —
// the STSubnet.trailLeafHash construction (evm/src/STSubnet.sol).

import (
	"math/big"
	"testing"
)

func repeat32(b byte) (out [32]byte) {
	for i := range out {
		out[i] = b
	}
	return
}

func TestTrailLeafGoldenSimple(t *testing.T) {
	// cast vector 1:
	// index=0, pathId=0x11*32, coverage=7, serverKeyId=1, finalDigest=0x22*32,
	// serverSigR=0x33*32, serverSigS=0x44*32, vpkSigR=0x55*32, vpkSigS=0x66*32
	leaf := TrailLeaf(
		0,
		repeat32(0x11),
		big.NewInt(7),
		1,
		repeat32(0x22),
		repeat32(0x33),
		repeat32(0x44),
		repeat32(0x55),
		repeat32(0x66),
	)
	want := "0xd3fdf0c58495ddab90b417152c118887d0458ea59c97e8ec8add489765a3c89e"
	if got := hex32([32]byte(leaf)); got != want {
		t.Fatalf("TrailLeaf golden 1: got %s want %s", got, want)
	}
}

func TestTrailLeafGoldenBoundary(t *testing.T) {
	// cast vector 2 — encoding extremes:
	// index=2^64-1, pathId=0xff*32, coverage=2^256-1, serverKeyId=2^64-1,
	// finalDigest=0x00*32,
	// serverSigR=0x00..ff (low byte set), serverSigS=0xff00..00 (high byte set),
	// vpkSigR=0x0102..20, vpkSigS=0x2021..3f
	var sigR1, sigS1, sigR2, sigS2 [32]byte
	sigR1[31] = 0xff
	sigS1[0] = 0xff
	for i := range sigR2 {
		sigR2[i] = byte(i + 1)  // 0x01..0x20
		sigS2[i] = byte(i + 32) // 0x20..0x3f
	}
	leaf := TrailLeaf(
		^uint64(0),
		repeat32(0xff),
		maxUint256(),
		^uint64(0),
		[32]byte{},
		sigR1,
		sigS1,
		sigR2,
		sigS2,
	)
	want := "0x94110e85ff48e71b93addb8b36079ff96a8d95e4d23ea38721b3fafa446fbbaa"
	if got := hex32([32]byte(leaf)); got != want {
		t.Fatalf("TrailLeaf golden 2: got %s want %s", got, want)
	}
}

// TestTrailLeafFieldSensitivity flips each field independently and requires a
// distinct hash — guarding against any two fields sharing a word slot.
func TestTrailLeafFieldSensitivity(t *testing.T) {
	base := func() Leaf {
		return TrailLeaf(1, repeat32(0x01), big.NewInt(2), 3, repeat32(0x04),
			repeat32(0x05), repeat32(0x06), repeat32(0x07), repeat32(0x08))
	}
	variants := []Leaf{
		TrailLeaf(9, repeat32(0x01), big.NewInt(2), 3, repeat32(0x04), repeat32(0x05), repeat32(0x06), repeat32(0x07), repeat32(0x08)),
		TrailLeaf(1, repeat32(0x99), big.NewInt(2), 3, repeat32(0x04), repeat32(0x05), repeat32(0x06), repeat32(0x07), repeat32(0x08)),
		TrailLeaf(1, repeat32(0x01), big.NewInt(9), 3, repeat32(0x04), repeat32(0x05), repeat32(0x06), repeat32(0x07), repeat32(0x08)),
		TrailLeaf(1, repeat32(0x01), big.NewInt(2), 9, repeat32(0x04), repeat32(0x05), repeat32(0x06), repeat32(0x07), repeat32(0x08)),
		TrailLeaf(1, repeat32(0x01), big.NewInt(2), 3, repeat32(0x99), repeat32(0x05), repeat32(0x06), repeat32(0x07), repeat32(0x08)),
		TrailLeaf(1, repeat32(0x01), big.NewInt(2), 3, repeat32(0x04), repeat32(0x99), repeat32(0x06), repeat32(0x07), repeat32(0x08)),
		TrailLeaf(1, repeat32(0x01), big.NewInt(2), 3, repeat32(0x04), repeat32(0x05), repeat32(0x99), repeat32(0x07), repeat32(0x08)),
		TrailLeaf(1, repeat32(0x01), big.NewInt(2), 3, repeat32(0x04), repeat32(0x05), repeat32(0x06), repeat32(0x99), repeat32(0x08)),
		TrailLeaf(1, repeat32(0x01), big.NewInt(2), 3, repeat32(0x04), repeat32(0x05), repeat32(0x06), repeat32(0x07), repeat32(0x99)),
	}
	seen := map[Leaf]bool{base(): true}
	for i, v := range variants {
		if seen[v] {
			t.Fatalf("variant %d collides with a previous leaf — field not bound into the hash", i)
		}
		seen[v] = true
	}
	if base() != base() {
		t.Fatal("TrailLeaf is not deterministic")
	}
}

// TestTrailLeafTree exercises trail leaves through the canonical tree: root
// stability under input reordering and OZ-style proof verification.
func TestTrailLeafTree(t *testing.T) {
	n := 13
	leaves := make([]Leaf, n)
	for i := 0; i < n; i++ {
		pathId := keccak256([]byte{byte(i), 0xaa})
		digest := keccak256([]byte{byte(i), 0xbb})
		leaves[i] = TrailLeaf(uint64(i), pathId, big.NewInt(int64(7+i)), 1, digest,
			keccak256([]byte{byte(i), 1}), keccak256([]byte{byte(i), 2}),
			keccak256([]byte{byte(i), 3}), keccak256([]byte{byte(i), 4}))
	}
	tree, err := NewTree(leaves)
	if err != nil {
		t.Fatal(err)
	}
	root := tree.Root()

	// Root is independent of input order.
	reversed := make([]Leaf, n)
	for i := range leaves {
		reversed[n-1-i] = leaves[i]
	}
	tree2, err := NewTree(reversed)
	if err != nil {
		t.Fatal(err)
	}
	if tree2.Root() != root {
		t.Fatal("root depends on input order")
	}

	// Every input-order proof verifies; a mutated leaf does not.
	for i := range leaves {
		proof, err := tree.ProofAt(i)
		if err != nil {
			t.Fatal(err)
		}
		if !Verify(root, leaves[i], proof) {
			t.Fatalf("proof %d does not verify", i)
		}
		bad := leaves[i]
		bad[0] ^= 1
		if Verify(root, bad, proof) {
			t.Fatalf("proof %d verified a mutated leaf", i)
		}
	}
}
