// gen_oz_fixtures.mjs — generates testdata/oz_fixtures.json from the REAL
// OpenZeppelin JS Merkle tree library, so the Go implementation in
// github.com/urnetwork/sn/merkle is tested against genuine OZ output
// rather than against itself.
//
// Source of truth: https://github.com/OpenZeppelin/merkle-tree
// (@openzeppelin/merkle-tree@1.0.8), StandardMerkleTree.of(values,
// ["bytes32", "uint256"]) with default options. Its leafHash is
// keccak256(bytes.concat(keccak256(abi.encode(bytes32, uint256)))) and its
// proofs verify with OZ contracts' MerkleProof.verify.
//
// Regenerate with:
//   npm install @openzeppelin/merkle-tree@1.0.8
//   node gen_oz_fixtures.mjs > oz_fixtures.json
//
// Cases marked verifyOnly:true have a leaf count (5) where the OZ JS
// library's packed-array tree layout differs from this package's canonical
// shape (sorted leaves, adjacent pairing, odd node promoted), so the ROOT
// legitimately differs while every OZ proof still verifies under the
// shared sorted-pair fold. All other cases coincide with the canonical
// shape and must match root and proofs exactly.

import { StandardMerkleTree } from "@openzeppelin/merkle-tree";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const ozVersion = require("@openzeppelin/merkle-tree/package.json").version;

const LEAF_ENCODING = ["bytes32", "uint256"];
const MAX_UINT256 =
  "115792089237316195423570985008687907853269984665640564039457584007913129639935"; // 2^256 - 1

const rep = (b) => "0x" + b.repeat(32);

const caseDefs = [
  {
    name: "oz_single",
    verifyOnly: false,
    values: [[rep("11"), "5000"]],
  },
  {
    name: "oz_pair",
    verifyOnly: false,
    values: [
      [rep("11"), "5000"],
      [rep("22"), "2500"],
    ],
  },
  {
    name: "oz_three",
    verifyOnly: false,
    values: [
      [rep("aa"), "0"],
      [rep("bb"), "10000"],
      [rep("cc"), MAX_UINT256],
    ],
  },
  {
    name: "oz_five",
    verifyOnly: true, // OZ JS array layout != canonical promoted-odd shape at n=5
    values: [
      [rep("01"), "100"],
      [rep("02"), "200"],
      [rep("03"), "300"],
      [rep("04"), "400"],
      [rep("05"), "500"],
    ],
  },
  {
    name: "oz_eight",
    verifyOnly: false,
    values: Array.from({ length: 8 }, (_, i) => [
      rep((i + 1).toString(16).padStart(2, "0")),
      String((i + 1) * 111),
    ]),
  },
];

const out = {
  source:
    `Generated by gen_oz_fixtures.mjs with @openzeppelin/merkle-tree@${ozVersion} ` +
    `(https://github.com/OpenZeppelin/merkle-tree): StandardMerkleTree.of(values, ` +
    `["bytes32","uint256"]), default options. leafHashes[i] = tree.leafHash(values[i]); ` +
    `proofs[i] = tree.getProof(values[i]); every proof re-checked with ` +
    `StandardMerkleTree.verify before writing.`,
  library: `@openzeppelin/merkle-tree@${ozVersion}`,
  leafEncoding: LEAF_ENCODING,
  cases: [],
};

for (const def of caseDefs) {
  const tree = StandardMerkleTree.of(def.values, LEAF_ENCODING);
  const entry = {
    name: def.name,
    verifyOnly: def.verifyOnly,
    leaves: def.values.map(([key, value]) => ({ key, value })),
    root: tree.root,
    leafHashes: def.values.map((v) => tree.leafHash(v)),
    proofs: def.values.map((v) => tree.getProof(v)),
  };
  // Self-check: every emitted proof must verify with the OZ library itself.
  for (const [i, v] of def.values.entries()) {
    if (!StandardMerkleTree.verify(entry.root, LEAF_ENCODING, v, entry.proofs[i])) {
      throw new Error(`self-check failed: ${def.name} leaf ${i}`);
    }
  }
  tree.validate();
  out.cases.push(entry);
}

process.stdout.write(JSON.stringify(out, null, 2) + "\n");
