// SPDX-License-Identifier: MPL-2.0
package main

import (
	"fmt"
	"regexp"
	"strings"
)

type declaration struct {
	result, name string
	params       []string
	unixOnly     bool
}

func declarations() (callbacks, functions []declaration) {
	cb := regexp.MustCompile(`^typedef (.+?) \(\*(urnet_\w+)\)\((.*)\);$`)
	fn := regexp.MustCompile(`^(.+?) (urnet_\w+)\((.*)\);$`)
	param := regexp.MustCompile(`^(.+?)\s+\w+$`)
	unixOnly := false
	for _, line := range strings.Split(string(read(path("cgo/include/urnetwork_sdk.h"))), "\n") {
		if line == "#if !defined(_WIN32)" {
			unixOnly = true
		}
		if line == "#endif /* !_WIN32 */" {
			unixOnly = false
		}
		m := cb.FindStringSubmatch(line)
		callback := m != nil
		if !callback {
			m = fn.FindStringSubmatch(line)
		}
		if m == nil {
			continue
		}
		d := declaration{result: m[1], name: m[2], unixOnly: unixOnly}
		if m[3] != "void" {
			for _, a := range strings.Split(m[3], ", ") {
				p := param.FindStringSubmatch(a)
				require(p != nil, "unknown C argument: %s", a)
				d.params = append(d.params, p[1])
			}
		}
		if callback {
			callbacks = append(callbacks, d)
		} else {
			functions = append(functions, d)
		}
	}
	found := false
	for _, d := range functions {
		if d.name == "urnet_abi_version" {
			found = true
		}
	}
	require(len(functions) >= 1000 && found, "incomplete C ABI header; run make -C cgo generate")
	return
}

func generateBindings() {
	callbacks, functions := declarations()
	types := strings.Split("void|bool|int32_t|int64_t|uint64_t|double|char*|const char*|void*|uint8_t*|const uint8_t*|bool*|int32_t*|char**", "|")
	typeMap := func(values string) map[string]string {
		valuesList := strings.Split(values, "|")
		require(len(valuesList) == len(types), "invalid generator type mapping")
		m := map[string]string{}
		for i, k := range types {
			m[k] = valuesList[i]
		}
		return m
	}
	py := typeMap("None|c_bool|c_int32|c_int64|c_uint64|c_double|c_void_p|c_char_p|c_void_p|POINTER(c_uint8)|POINTER(c_uint8)|POINTER(c_bool)|POINTER(c_int32)|POINTER(c_void_p)")
	java := typeMap("void|byte|int|long|long|double|Pointer|String|Pointer|Pointer|Pointer|ByteByReference|IntByReference|PointerByReference")
	cs := typeMap("void|byte|int|long|ulong|double|IntPtr|[MarshalAs(UnmanagedType.LPUTF8Str)] string|IntPtr|IntPtr|IntPtr|out byte|ref int|out IntPtr")
	rs := typeMap("()|bool|i32|i64|u64|f64|*mut c_char|*const c_char|*mut c_void|*mut u8|*const u8|*mut bool|*mut i32|*mut *mut c_char")
	rb := typeMap(":void|:bool|:int32|:int64|:uint64|:double|:pointer|:string|:pointer|:pointer|:pointer|:pointer|:pointer|:pointer")
	for _, c := range callbacks {
		for _, m := range []map[string]string{py, java, cs, rs} {
			m[c.name] = c.name
		}
		rb[c.name] = ":" + c.name
	}
	lookup := func(m map[string]string, t string) string {
		v, ok := m[t]
		require(ok, "unknown C type: %s", t)
		return v
	}
	args := func(d declaration, m map[string]string, names bool) string {
		result := []string{}
		for i, t := range d.params {
			v := lookup(m, t)
			if names {
				v += fmt.Sprintf(" a%d", i)
			}
			result = append(result, v)
		}
		return strings.Join(result, ", ")
	}
	var p, j, c, r, b strings.Builder
	p.WriteString("# Generated by packaging/generate.go. Do not edit.\nfrom ctypes import *\nimport os\n\n")
	j.WriteString("// Generated by packaging/generate.go. Do not edit.\npackage io.ur.sdk;\nimport com.sun.jna.*;\nimport com.sun.jna.ptr.*;\npublic interface Raw extends Library {\n")
	c.WriteString("// Generated by packaging/generate.go. Do not edit.\nusing System;\nusing System.Runtime.InteropServices;\nnamespace URnetwork.SDK;\npublic static partial class Raw {\n")
	r.WriteString("// Generated by packaging/generate.go. Do not edit.\n#![allow(non_camel_case_types)]\nuse std::ffi::{c_char, c_void};\n")
	b.WriteString("# Generated by packaging/generate.go. Do not edit.\nmodule URnetwork\n  module Raw\n    def self.bind_functions\n")
	for _, d := range callbacks {
		a := args(d, py, false)
		if a != "" {
			a = ", " + a
		}
		fmt.Fprintf(&p, "%s = CFUNCTYPE(%s%s)\n", d.name, lookup(py, d.result), a)
		fmt.Fprintf(&j, "  interface %s extends Callback { %s invoke(%s); }\n", d.name, lookup(java, d.result), args(d, java, true))
		fmt.Fprintf(&c, "  [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate %s %s(%s);\n", lookup(cs, d.result), d.name, args(d, cs, true))
		fmt.Fprintf(&r, "pub type %s = Option<unsafe extern \"C\" fn(%s) -> %s>;\n", d.name, args(d, rs, false), lookup(rs, d.result))
		fmt.Fprintf(&b, "      callback :%s, [%s], %s\n", d.name, args(d, rb, false), lookup(rb, d.result))
	}
	p.WriteString("\ndef bind(lib):\n")
	r.WriteString("pub struct Raw {\n    _library: libloading::Library,\n")
	for _, d := range functions {
		indent := "    "
		rubyGuard := ""
		if d.unixOnly {
			p.WriteString("    if os.name != \"nt\":\n")
			indent += "    "
			r.WriteString("    #[cfg(not(windows))]\n")
			rubyGuard = " unless FFI::Platform.windows?"
		}
		fmt.Fprintf(&p, "%slib.%s.argtypes = [%s]\n%slib.%s.restype = %s\n", indent, d.name, args(d, py, false), indent, d.name, lookup(py, d.result))
		fmt.Fprintf(&j, "  %s %s(%s);\n", lookup(java, d.result), d.name, args(d, java, true))
		fmt.Fprintf(&c, "  [DllImport(\"URnetworkSdk\", CallingConvention = CallingConvention.Cdecl)] public static extern %s %s(%s);\n", lookup(cs, d.result), d.name, args(d, cs, true))
		fmt.Fprintf(&r, "    pub %s: unsafe extern \"C\" fn(%s) -> %s,\n", d.name, args(d, rs, false), lookup(rs, d.result))
		fmt.Fprintf(&b, "      attach_function :%s, [%s], %s, blocking: true%s\n", d.name, args(d, rb, false), lookup(rb, d.result), rubyGuard)
	}
	r.WriteString("}\nimpl Raw {\n    /// # Safety\n    /// The library must implement the exact URnetwork C ABI declared here.\n    pub unsafe fn load(path: &std::path::Path) -> Result<Self, libloading::Error> {\n        let library = unsafe { libloading::Library::new(path)? };\n        Ok(Self {\n")
	for _, d := range functions {
		if d.unixOnly {
			r.WriteString("            #[cfg(not(windows))]\n")
		}
		fmt.Fprintf(&r, "            %s: unsafe { *library.get(b\"%s\\0\")? },\n", d.name, d.name)
	}
	r.WriteString("            _library: library,\n        })\n    }\n}\n")
	textFile(path("python/src/urnetwork/_raw.py"), p.String())
	textFile(path("java/src/main/java/io/ur/sdk/Raw.java"), j.String()+"}\n")
	textFile(path("csharp/Raw.g.cs"), c.String()+"}\n")
	textFile(path("rust/src/raw.rs"), r.String())
	textFile(path("ruby/lib/urnetwork/raw.rb"), b.String()+"    end\n  end\nend\n")
	fmt.Printf("Generated %d functions and %d callbacks for five bindings\n", len(functions), len(callbacks))
}
