// SPDX-License-Identifier: MPL-2.0
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"
)

func buildPython() string {
	venv := path("packaging/.venv")
	executable := filepath.Join(venv, "bin/python")
	if runtime.GOOS == "windows" {
		executable = filepath.Join(venv, "Scripts/python.exe")
	}
	if !exists(executable) {
		command(root, nil, env("PYTHON", "python3"), "-m", "venv", venv)
		command(root, nil, executable, "-m", "pip", "install", "build==1.3.0", "wheel==0.45.1")
	}
	return executable
}
func minimumOS(system, binary string) string {
	switch system {
	case "darwin":
		m := regexp.MustCompile(`\bminos\s+([0-9.]+)`).FindSubmatch(output(root, nil, "otool", "-l", binary))
		require(m != nil, "cannot determine native macOS minimum")
		return string(m[1])
	case "linux":
		v := strings.TrimSpace(string(output(root, nil, "getconf", "GNU_LIBC_VERSION")))
		require(strings.HasPrefix(v, "glibc "), "set SDK_NATIVE_MINIMUM_OS for this Linux toolchain")
		return strings.Replace(v, " ", "-", 1)
	case "windows":
		return "windows-10"
	}
	panic("unsupported OS")
}
func loadNative() nativeManifest {
	if p := os.Getenv("SDK_NATIVE_MANIFEST"); p != "" {
		p, e := filepath.Abs(p)
		must(e)
		var m nativeManifest
		jsonRead(p, &m)
		require(m.ABI == 1 && len(m.Libraries) > 0, "invalid native manifest")
		seen := map[string]bool{}
		for i := range m.Libraries {
			entry := &m.Libraries[i]
			require(!seen[entry.Platform], "duplicate native platform: %s", entry.Platform)
			seen[entry.Platform] = true
			if !filepath.IsAbs(entry.Path) {
				entry.Path = filepath.Join(filepath.Dir(p), entry.Path)
			}
			require(hash(entry.Path) == entry.SHA256, "native checksum mismatch: %s", entry.Platform)
			require(entry.MinimumOS != "", "native manifest requires minimum_os")
		}
		if v := os.Getenv("WARP_VERSION"); v != "" {
			require(m.Version == v, "native version does not match WARP_VERSION")
		}
		return m
	}
	filename, ok := files[runtime.GOOS]
	require(ok, "unsupported native host")
	target := runtime.GOOS + "-" + runtime.GOARCH
	out := path("cgo/build/packages", target, filename)
	mkdir(filepath.Dir(out))
	match := regexp.MustCompile(`(github.com/urnetwork/sdk(?:/v[0-9]+)?)\s+v`).FindSubmatch(read(path("cgo/go.mod")))
	require(match != nil, "SDK module dependency absent")
	v := env("WARP_VERSION", packageVersion())
	command(path("cgo"), map[string]string{"CGO_ENABLED": "1"}, "go", "build", "-trimpath", "-buildmode=c-shared", "-ldflags", "-s -w -X "+string(match[1])+".Version="+v, "-o", out, ".")
	if runtime.GOOS == "darwin" {
		command(root, nil, "install_name_tool", "-id", "@rpath/"+filename, out)
		command(root, nil, "codesign", "--force", "--sign", "-", out)
	}
	minimum := os.Getenv("SDK_NATIVE_MINIMUM_OS")
	if minimum == "" {
		minimum = minimumOS(runtime.GOOS, out)
	}
	m := nativeManifest{ABI: 1, Version: v, Libraries: []library{{Platform: target, Path: out, SHA256: hash(out), MinimumOS: minimum}}}
	jsonWrite(path("cgo/build/packages/manifest.json"), m)
	return m
}
func publicNative(m nativeManifest) nativeManifest {
	result := m
	result.Libraries = append([]library(nil), m.Libraries...)
	for i := range result.Libraries {
		result.Libraries[i].Path = ""
	}
	return result
}
func stageNative(language, destination string, m nativeManifest) {
	subpath, ok := nativePaths[language]
	require(ok, "unknown package language: %s", language)
	target := filepath.Join(destination, subpath)
	must(os.RemoveAll(target))
	mkdir(target)
	var code strings.Builder
	code.WriteString("// Generated by packaging/package.go. Runtime bytes are versioned with the crate.\n")
	cfgs := []string{}
	for _, entry := range m.Libraries {
		system, arch, ok := strings.Cut(entry.Platform, "-")
		require(ok && files[system] != "" && (arch == "arm64" || arch == "amd64"), "unsupported native platform")
		subdir := entry.Platform
		if language == "csharp" {
			subdir = map[string]string{"darwin": "osx", "linux": "linux", "windows": "win"}[system] + "-" + map[string]string{"amd64": "x64", "arm64": "arm64"}[arch] + "/native"
		}
		out := filepath.Join(target, subdir, files[system])
		if language == "rust" {
			gzipFile(entry.Path, out+".gz")
			cfg := fmt.Sprintf("all(target_os = %q, target_arch = %q)", map[string]string{"darwin": "macos", "linux": "linux", "windows": "windows"}[system], map[string]string{"amd64": "x86_64", "arm64": "aarch64"}[arch])
			cfgs = append(cfgs, cfg)
			fmt.Fprintf(&code, "#[cfg(%s)]\npub fn packaged() -> Option<(&'static [u8], &'static str, &'static str)> { Some((include_bytes!(%q), %q, %q)) }\n", cfg, "../native/"+entry.Platform+"/"+files[system]+".gz", entry.SHA256, files[system])
		} else {
			copyFile(entry.Path, out)
		}
	}
	jsonWrite(filepath.Join(target, "manifest.json"), publicNative(m))
	if language == "rust" {
		fmt.Fprintf(&code, "#[cfg(not(any(%s)))]\npub fn packaged() -> Option<(&'static [u8], &'static str, &'static str)> { None }\n", strings.Join(cfgs, ", "))
		textFile(filepath.Join(destination, "src/runtime.rs"), code.String())
	}
}
func languageVersion(language, version string) string {
	switch language {
	case "python":
		v := regexp.MustCompile(`-([0-9]+)$`).ReplaceAllString(version, ".dev$1")
		v = strings.Replace(v, "-dev.", ".dev", 1)
		require(!strings.Contains(v, "-"), "unsupported Python prerelease spelling: %s", version)
		return v
	case "ruby":
		return strings.ReplaceAll(version, "-", ".pre.")
	}
	return version
}
func wheelPlatform(e library) string {
	system, arch, _ := strings.Cut(e.Platform, "-")
	switch system {
	case "windows":
		return map[string]string{"amd64": "win_amd64", "arm64": "win_arm64"}[arch]
	case "darwin":
		parts := strings.Split(e.MinimumOS, ".")
		major, err := strconv.Atoi(parts[0])
		must(err)
		minor := 0
		if len(parts) > 1 {
			minor, err = strconv.Atoi(parts[1])
			must(err)
		}
		if major >= 11 && minor > 0 {
			major++
			minor = 0
		}
		return fmt.Sprintf("macosx_%d_%d_%s", major, minor, map[string]string{"amd64": "x86_64", "arm64": "arm64"}[arch])
	case "linux":
		require(regexp.MustCompile(`^glibc-2\.\d+$`).MatchString(e.MinimumOS), "Linux wheel requires an audited glibc floor")
		return "manylinux_" + strings.ReplaceAll(strings.TrimPrefix(e.MinimumOS, "glibc-"), ".", "_") + "_" + map[string]string{"amd64": "x86_64", "arm64": "aarch64"}[arch]
	}
	panic("unknown wheel target")
}
func stagedProject(language, out string) string {
	stage := filepath.Join(out, "project")
	must(os.RemoveAll(stage))
	skip := map[string]bool{}
	for _, s := range []string{"build", "dist", "target", "obj", "bin", "native", "runtimes", "__pycache__"} {
		skip[s] = true
	}
	copyTree(path(language), stage, skip)
	copyFile(path("LICENSE"), filepath.Join(stage, "LICENSE"))
	for _, name := range []string{"pyproject.toml", "pom.xml", "Cargo.toml", "urnetwork-sdk.gemspec", "URnetwork.SDK.csproj"} {
		p := filepath.Join(stage, name)
		if !exists(p) {
			continue
		}
		s := string(read(p))
		for _, old := range []string{"0.0.1-dev.0", "0.0.1.pre.dev.0", "0.0.1.dev0"} {
			s = strings.ReplaceAll(s, old, languageVersion(language, packageVersion()))
		}
		textFile(p, s)
	}
	return stage
}
func stageRustRelease(stage, assets string, m nativeManifest) {
	public := publicNative(m)
	mkdir(assets)
	for i := range public.Libraries {
		e := &public.Libraries[i]
		system, _, _ := strings.Cut(e.Platform, "-")
		name := "URnetworkSdk-" + packageVersion() + "-" + e.Platform + ".gz"
		artifact := filepath.Join(assets, name)
		gzipFile(m.Libraries[i].Path, artifact)
		e.Filename = files[system]
		e.Archive = name
		e.ArchiveSHA256 = hash(artifact)
		e.URL = "https://github.com/urnetwork/build/releases/download/v" + packageVersion() + "/" + name
	}
	jsonWrite(filepath.Join(stage, "native/manifest.json"), public)
	textFile(filepath.Join(stage, "src/runtime.rs"), "include!(concat!(env!(\"OUT_DIR\"), \"/runtime.rs\"));\n")
}
func buildPackage(language string, m nativeManifest, out string) {
	_, ok := nativePaths[language]
	require(ok, "unknown package language")
	artifacts := filepath.Join(out, "artifacts")
	must(os.RemoveAll(artifacts))
	mkdir(artifacts)
	stage := stagedProject(language, out)
	switch language {
	case "python", "ruby":
		for _, entry := range m.Libraries {
			single := m
			single.Libraries = []library{entry}
			stageNative(language, stage, single)
			if language == "python" {
				must(os.RemoveAll(filepath.Join(stage, "build")))
				command(stage, map[string]string{"SDK_WHEEL_PLATFORM": wheelPlatform(entry)}, buildPython(), "-m", "build", "--wheel", "--outdir", artifacts)
			} else {
				system, arch, _ := strings.Cut(entry.Platform, "-")
				cpu := map[string]string{"amd64": "x86_64", "arm64": "aarch64"}[arch]
				if arch == "arm64" && system == "darwin" {
					cpu = "arm64"
				}
				platform := cpu + "-" + map[string]string{"darwin": "darwin", "linux": "linux", "windows": "mingw-ucrt"}[system]
				command(stage, map[string]string{"SDK_GEM_PLATFORM": platform}, "gem", "build", "urnetwork-sdk.gemspec", "--output", filepath.Join(artifacts, "urnetwork-sdk-"+languageVersion(language, packageVersion())+"-"+platform+".gem"))
			}
		}
		if language == "python" {
			must(os.RemoveAll(filepath.Join(stage, nativePaths[language])))
			command(stage, nil, buildPython(), "-m", "build", "--sdist", "--outdir", artifacts)
		}
	case "java":
		stageNative(language, stage, m)
		command(stage, nil, "mvn", "-B", "-q", "package")
		for _, p := range glob(filepath.Join(stage, "target/*.jar")) {
			copyFile(p, filepath.Join(artifacts, filepath.Base(p)))
		}
		copyFile(filepath.Join(stage, "pom.xml"), filepath.Join(artifacts, "urnetwork-sdk-"+packageVersion()+".pom"))
	case "csharp":
		stageNative(language, stage, m)
		d := requireDotnet()
		command(stage, d.environment(nil), d.executable, "pack", "-c", "Release", "-o", artifacts)
	case "rust":
		e := map[string]string{}
		if assets := os.Getenv("SDK_RUST_RELEASE_ASSETS"); assets != "" {
			stageRustRelease(stage, assets, m)
			e["SDK_RUST_NATIVE_CACHE"] = assets
		} else {
			stageNative(language, stage, m)
		}
		command(stage, e, "cargo", "package", "--allow-dirty")
		for _, p := range glob(filepath.Join(stage, "target/package/*.crate")) {
			copyFile(p, filepath.Join(artifacts, filepath.Base(p)))
		}
	}
	jsonWrite(filepath.Join(out, "manifest.json"), inventory{Version: packageVersion(), Native: &m, Artifacts: artifactsIn(artifacts)})
	fmt.Println("Built", language, artifacts)
}
