vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
if(VCPKG_TARGET_IS_OSX)
  set(_ur_os darwin)
elseif(VCPKG_TARGET_IS_LINUX)
  set(_ur_os linux)
elseif(VCPKG_TARGET_IS_WINDOWS)
  set(_ur_os windows)
else()
  message(FATAL_ERROR "Unsupported URnetwork platform")
endif()
if(VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
  set(_ur_arch amd64)
elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "arm64")
  set(_ur_arch arm64)
else()
  message(FATAL_ERROR "Unsupported URnetwork architecture")
endif()
file(READ "${CURRENT_PORT_DIR}/native.json" _ur_index)
string(JSON _ur_count LENGTH "${_ur_index}" assets)
math(EXPR _ur_last "${_ur_count} - 1")
set(_ur_found FALSE)
foreach(_ur_i RANGE "${_ur_last}")
  string(JSON _ur_platform GET "${_ur_index}" assets ${_ur_i} platform)
  if(_ur_platform STREQUAL "${_ur_os}-${_ur_arch}")
    string(JSON _ur_url GET "${_ur_index}" assets ${_ur_i} url)
    string(JSON _ur_name GET "${_ur_index}" assets ${_ur_i} archive)
    string(JSON _ur_sha GET "${_ur_index}" assets ${_ur_i} sha512)
    vcpkg_download_distfile(ARCHIVE URLS "${_ur_url}" FILENAME "${_ur_name}" SHA512 "${_ur_sha}")
    vcpkg_extract_source_archive(SOURCE_PATH ARCHIVE "${ARCHIVE}" NO_REMOVE_ONE_LEVEL)
    file(COPY "${SOURCE_PATH}/include" "${SOURCE_PATH}/lib" "${SOURCE_PATH}/share" DESTINATION "${CURRENT_PACKAGES_DIR}")
    if(EXISTS "${SOURCE_PATH}/bin")
      file(COPY "${SOURCE_PATH}/bin" DESTINATION "${CURRENT_PACKAGES_DIR}")
    endif()
    # The Go engine has one ABI for debug and release C/C++ consumers.
    file(COPY "${SOURCE_PATH}/lib" DESTINATION "${CURRENT_PACKAGES_DIR}/debug")
    if(EXISTS "${SOURCE_PATH}/bin")
      file(COPY "${SOURCE_PATH}/bin" DESTINATION "${CURRENT_PACKAGES_DIR}/debug")
    endif()
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/lib/cmake")
    set(_ur_found TRUE)
  endif()
endforeach()
if(NOT _ur_found)
  message(FATAL_ERROR "This SDK release has no runtime for this target")
endif()
