name: Build AAR

on:
  workflow_dispatch: # Allows manual triggering
  pull_request:
    branches:
      - main

jobs:
  build_aar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "zulu"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"

      - name: build patched go
        run: |
          git config --global user.email "build@ur.io"
          git config --global user.name "Urnetrwork Build"

          git clone https://go.googlesource.com/go gosource
          cd gosource
          git checkout -b patched-1.23.3 go1.23.3
          git revert -n 3560cf0afb3c29300a6c88ccd98256949ca7a6f6
          cd src
          ./make.bash
          cd ..
          ls -laR bin
          go version
          set -x
          cp ./bin/go "$(which go)"
          go version
          cd ..
          rm -rf gosource
      - name: fix go mod
        run: |
          go mod edit -dropreplace github.com/urnetwork/connect@v0.0.0
          go mod edit -dropreplace github.com/urnetwork/protocol@v0.0.0
          go mod edit -dropreplace github.com/urnetwork/userwireguard@v0.0.0

          go mod edit -require github.com/urnetwork/connect@latest -require github.com/urnetwork/protocol@latest -require github.com/urnetwork/userwireguard@latest
          go mod tidy

      - name: install gomobile
        run: go install golang.org/x/mobile/cmd/...@latest

      - name: build
        run: |
          mkdir -p build/android
          gomobile bind \
            -target=android/arm64,android/arm,android/amd64 -androidapi 24 \
            -javapkg com.bringyour \
            -trimpath \
            -gcflags="-dwarf=true" \
            -ldflags="-X client.Version="1.2.3" -compressdwarf=false -B gobuildid" \
            -o build/android/URnetworkSdk.aar \
            github.com/urnetwork/sdk

      - name: validate
        run: |
          cd build/android
          mkdir validate

          cp URnetworkSdk-sources.jar validate/
          cd validate
          jar -xf URnetworkSdk-sources.jar
          set -x
          bad_exports="$(grep -Ri '// skipped' . || echo -n)"
          if [[ "$bad_exports" ]]; then
              echo "Some types could not be exported:"
              echo "$bad_exports"
              exit 1
          fi
