name: Build Release

permissions:
  contents: write

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    # Run daily at 11:00 AM Pacific Time (Standard Time: 19:00 UTC, DST: 18:00 UTC)
    - cron: "0 19 * * *" # Update to '0 18 * * *' during DST if needed

jobs:
  build_aar:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SDK_PRIVATE_KEY }}" > ~/.ssh/sdk_key
          chmod 600 ~/.ssh/sdk_key

          # Create SSH config file
          echo "Host github-sdk-key" >> ~/.ssh/config
          echo "  HostName github.com" >> ~/.ssh/config
          echo "  User git" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/sdk_key" >> ~/.ssh/config

          # Add GitHub to known_hosts to avoid prompt
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone Repo
        run: |
          git clone git@github-sdk-key:urnetwork/sdk.git

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "zulu"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"

      - name: build patched go
        run: |
          git config --global user.email "build@ur.io"
          git config --global user.name "Urnetrwork Build"

          git clone https://go.googlesource.com/go gosource
          cd gosource
          git checkout -b patched-1.23.3 go1.23.3
          git revert -n 3560cf0afb3c29300a6c88ccd98256949ca7a6f6
          cd src
          ./make.bash
          cd ..
          ls -laR bin
          go version
          set -x
          cp ./bin/go "$(which go)"
          go version
          cd ..
          rm -rf gosource

      - name: fix go mod
        working-directory: sdk
        run: |
          go mod edit -dropreplace github.com/urnetwork/connect@v0.0.0
          go mod edit -dropreplace github.com/urnetwork/protocol@v0.0.0
          go mod edit -dropreplace github.com/urnetwork/userwireguard@v0.0.0

          go mod edit -require github.com/urnetwork/connect@latest -require github.com/urnetwork/protocol@latest -require github.com/urnetwork/userwireguard@latest
          go mod tidy

      - name: install gomobile
        run: go install golang.org/x/mobile/cmd/...@latest

      - name: build
        working-directory: sdk
        run: |
          mkdir -p build/android
          gomobile bind \
            -target=android/arm64,android/arm,android/amd64 -androidapi 24 \
            -javapkg com.bringyour \
            -trimpath \
            -gcflags="-dwarf=true" \
            -ldflags="-X client.Version="1.2.3" -compressdwarf=false -B gobuildid" \
            -o build/android/URnetworkSdk.aar \
            github.com/urnetwork/sdk

      - name: validate
        working-directory: sdk
        run: |
          cd build/android
          mkdir validate

          cp URnetworkSdk-sources.jar validate/
          cd validate
          jar -xf URnetworkSdk-sources.jar
          set -x
          bad_exports="$(grep -Ri '// skipped' . || echo -n)"
          if [[ "$bad_exports" ]]; then
              echo "Some types could not be exported:"
              echo "$bad_exports"
              exit 1
          fi

          find .
          ls -alr

      - name: Install semver-release
        run: go install github.com/urnetwork/semver-release@v0.0.6

      - name: Create Release
        working-directory: sdk
        id: create-release
        run: |
          PREVIOUS_RELEASE="$($HOME/go/bin/semver-release latest .)"
          $HOME/go/bin/semver-release release
          git push origin --tags
          CURRENT_RELEASE="$($HOME/go/bin/semver-release latest .)"

          set -x
          git log "v$PREVIOUS_RELEASE".."v$CURRENT_RELEASE" --oneline

          echo "version=$($HOME/go/bin/semver-release latest .)" >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: "comnoco/create-release-action@v2"
        with:
          tag_name: v${{steps.create-release.outputs.version}}
          release_name: Release ${{steps.create-release.outputs.version}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This is a nightly release
      - name: Upload aar
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sdk/build/android/URnetworkSdk.aar
          asset_name: mything
          tag: v${{steps.create-release.outputs.version}}
          overwrite: true
          body: "urnetwork client aar"
